# Generated by Django 3.0.5 on 2020-04-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=15)),
                ('receiver', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timeSent', models.DateTimeField(auto_now_add=True)),
                ('timeReceived', models.DateTimeField()),
            ],
        ),
    ]
